version: '3.3'

services:
  postgis:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: nepaldata
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    links:
      - postgis

  osm2pgsql:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    links:
      - postgis
    volumes:
      - ./data/nepal-latest.osm.pbf:/tmp/nepal-latest.osm.pbf

volumes:
  db_data: